names['British Empire'] = [
// Royal Marines serving between 1860 and 1870

"John Thomas Draper",
"James Baker",
"George Robinson",
"John Samson",
"Samuel Buckman",
"James Borrett",
"Walter J. J. Gunn",
"Charles Riseborough",
"Arthur Grey",
"Charles J. Thomas",
"John Jones",
"George James Taylor",
"Walter Jewell",
"John Devereux",
"Jesse Hutson",
"Samuel Hipgrave",
"George Collard",
"Isaac Pollintine",
"Walter Willcocks",
"John Boyas",
"Francis Pritchard",
"George Newbery King",
"George White",
"Frederick William Butler",
"John Dunn",
"Thomas Reed",
"Ernest Coghlan",
"James Divenish",
"Frederick Whitlock",
"Thomas Woollams",

];
