names['French Empire'] = [

// French soldiers who participated in the Battle of Trafalgar

"Jean Pierre Roustant",
"Felix Jacon",
"Pierre Feburier",
"Joseph Lebayle",
"Guillaume Rogue",
"Francois Saillard",
"Charles Foullon",
"Joseph Peyron",
"Jacques Blanchon",
"Laurent Landry",
"Marial Martin",
"Marc Antoine Giraud",
"Nicolas Collignon",
"Jean Marie Fayeulle",
"Joseph Roger",
"Jacques Bonhumme",
"Jean Maraux",
"Nicolas Chelin",
"Jean Nicolas Bernard",
"Jean Javaux",
"Jacques Lubjoie",
"Antoine Aubain",
"Pierre Chouleur",
"Jean Maurice Arrissart",
"Joseph Langlais",
"Jean Baptiste Fillier",
"Louis Sebastien Paijen",
"Jean B Bauzard",
"Jean Germain Denant",
"Louis Antoine Feraud",
"Auguste Serrier",
"Charles Alexandre Raillard",
"Pierre Rogue",
"Julien Jean Saillard",
"Louis C Paillard",
"Cesar Dautpoule",
"Auguste Delahuiliniere",
"Andre Nerciat",
"Honore Masse",
"Hypolyte Cruchier",
"Vincent Hipolyte Figuier",
"Xavier Bonnafos",

];
