names['United Mexican States'] = [

// Mexican men who died in Oaxaca in 1870

"Gregorio Mateo",
"Manuel Patrosinio",
"Mariano Ignacio",
"Leonardo Pedro",
"Juan Capistrano",
"Juan Esteban",
"Anastasio Vicente",
"Clemente Pedro",
"Feliciano Alejando",
"Gabriel Bautista Santiago",
"José María",
"Juan Antonio",
"Salvador Luiz",
"Vicente Hilario",
"Inacio Francisco",
"Manuel Pedro",
"Vicente Felipe",
"Miguel Juan Jose",
"Florencío Mariano",
"Pedro Francisco",
"José Mateo",
"Victoriano Mareano",
"Antonio Diego",
"Antonio Hilario",
"Feliciano Bartolomé",
"Esteban José Maria",
"Leveriano José",
"Luis Pedro",
"Matias Pedro",
"Pedro Matias",
"Tiburcio Miguel",
"Agustin Juan",
"Anastasio Antonio",
"Manuel Martin",
"Domingo Ambrosio",

];
